name: Secrets

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: ".src/GithubActionsDotNet.Api/GithubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"

     
